# Generated by Django 4.0.1 on 2022-01-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_cidade_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='img',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
